services:
  web:
    build:
      context: .
    container_name: myblog
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # deploy.sh 스크립트 실행용

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    expose:
      - "6379"

volumes:
  caddy_data:
  caddy_config:
  redis_data: