services:
  web:
    build:
      context: .
      args:
        # STRAPI_URL: https://grounded-rainbow-3b0e27f8c5.strapiapp.com
        # NEXT_PUBLIC_CMS_URL: https://grounded-rainbow-3b0e27f8c5.strapiapp.com
        # Strapi-related args commented out - now using markdown files
    container_name: myblog
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "3000"

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    expose:
      - "6379"

volumes:
  caddy_data:
  caddy_config:
  redis_data:
