services:
  web:
    build:
      context: .
    container_name: myblog
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"  # 호스트에서 접근 가능하도록 포트 매핑
    volumes:
      - ./content:/app/content # 컨텐츠 파일을 컨테이너와 공유
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    expose:
      - "6379"

volumes:
  caddy_data:
  caddy_config:
  redis_data: