import { PostOrPage } from '@tryghost/content-api';

export const dummyPosts: PostOrPage[] = [
  {
    id: 'dummy-1',
    uuid: 'dummy-uuid-1',
    title: '첫 번째 더미 게시글',
    slug: 'first-dummy-post',
    html: '<p>이것은 첫 번째 더미 게시글의 내용입니다.</p>',
    feature_image: 'https://via.placeholder.com/1000x400.png?text=Dummy+Post+1',
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    excerpt: '첫 번째 더미 게시글의 요약입니다.',
    reading_time: 2,
    access: true,
    comments: false,
    visibility: 'public',
    // 실제 API 응답에는 더 많은 필드가 있을 수 있습니다.
    // 필요에 따라 tags, authors 등을 추가하세요.
    tags: [{ id: 'tag-1', name: 'Dummy Tag', slug: 'dummy-tag', description: null, feature_image: null, visibility: 'public', og_image: null, og_title: null, og_description: null, twitter_image: null, twitter_title: null, twitter_description: null, meta_title: null, meta_description: null, codeinjection_head: null, codeinjection_foot: null, canonical_url: null, accent_color: null, url: '/tag/dummy-tag/'}],
    authors: [{ id: 'author-1', name: 'Dummy Author', slug: 'dummy-author', profile_image: null, cover_image: null, bio: null, website: null, location: null, facebook: null, twitter: null, meta_title: null, meta_description: null, url: '/author/dummy-author/' }],
    primary_tag: { id: 'tag-1', name: 'Dummy Tag', slug: 'dummy-tag', description: null, feature_image: null, visibility: 'public', og_image: null, og_title: null, og_description: null, twitter_image: null, twitter_title: null, twitter_description: null, meta_title: null, meta_description: null, codeinjection_head: null, codeinjection_foot: null, canonical_url: null, accent_color: null, url: '/tag/dummy-tag/'},
    primary_author: { id: 'author-1', name: 'Dummy Author', slug: 'dummy-author', profile_image: null, cover_image: null, bio: null, website: null, location: null, facebook: null, twitter: null, meta_title: null, meta_description: null, url: '/author/dummy-author/' },
    url: '/first-dummy-post/',
    canonical_url: null,
    codeinjection_head: null,
    codeinjection_foot: null,
    custom_excerpt: null,
    custom_template: null,
    email_recipient_filter: 'all',
    email_subject: null,
    frontmatter: null,
    meta_description: null,
    meta_title: null,
    og_description: null,
    og_image: null,
    og_title: null,
    send_email_when_published: false,
    twitter_description: null,
    twitter_image: null,
    twitter_title: null,
    comment_id: 'dummy-1'
  },
  {
    id: 'dummy-2',
    uuid: 'dummy-uuid-2',
    title: '두 번째 더미 게시글',
    slug: 'second-dummy-post',
    html: '<p>두 번째 더미 게시글의 내용입니다. <strong>굵은 텍스트</strong>와 <em>기울임꼴 텍스트</em>를 포함합니다.</p>',
    feature_image: 'https://via.placeholder.com/1000x400.png?text=Dummy+Post+2',
    published_at: new Date(Date.now() - 86400000).toISOString(), // 어제
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    excerpt: '두 번째 더미 게시글의 요약입니다.',
    reading_time: 3,
    access: true,
    comments: false,
    visibility: 'public',
    tags: [],
    authors: [{ id: 'author-1', name: 'Dummy Author', slug: 'dummy-author', profile_image: null, cover_image: null, bio: null, website: null, location: null, facebook: null, twitter: null, meta_title: null, meta_description: null, url: '/author/dummy-author/' }],
    primary_tag: null,
    primary_author: { id: 'author-1', name: 'Dummy Author', slug: 'dummy-author', profile_image: null, cover_image: null, bio: null, website: null, location: null, facebook: null, twitter: null, meta_title: null, meta_description: null, url: '/author/dummy-author/' },
    url: '/second-dummy-post/',
    canonical_url: null,
    codeinjection_head: null,
    codeinjection_foot: null,
    custom_excerpt: null,
    custom_template: null,
    email_recipient_filter: 'all',
    email_subject: null,
    frontmatter: null,
    meta_description: null,
    meta_title: null,
    og_description: null,
    og_image: null,
    og_title: null,
    send_email_when_published: false,
    twitter_description: null,
    twitter_image: null,
    twitter_title: null,
    comment_id: 'dummy-2'
  },
  // 필요에 따라 더 많은 더미 게시글 추가
];

// 페이지 등 다른 종류의 더미 데이터도 필요하면 여기에 추가할 수 있습니다.
// export const dummyPages: PostOrPage[] = [...] 